spring:
        datasource:
            driverClassName: org.postgresql.Driver
            url: jdbc:postgresql://localhost:5432/study-db
            jdbc-url: jdbc:postgresql://localhost:5432/study-db
            username: postgres
            password: postgres
